# Generated by Django 4.2.4 on 2024-03-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
