# Generated by Django 4.2.4 on 2024-03-08 06:42

from django.db import migrations, models
import webpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_remove_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to=webpage.models.user_directory_path),
        ),
    ]
